import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const index = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const main = readFileSync(new URL('./main.js', import.meta.url), 'utf8');
const audio = readFileSync(new URL('./audio.js', import.meta.url), 'utf8');
const chat = readFileSync(new URL('./multiplayer/text_chat.js', import.meta.url), 'utf8');
const runtime = readFileSync(new URL('./crazygames.js', import.meta.url), 'utf8');
const release = JSON.parse(readFileSync(new URL('../release-version.json', import.meta.url), 'utf8'));
const manifest = JSON.parse(readFileSync(new URL('../multiplayer-release.json', import.meta.url), 'utf8'));
assert.match(index, /crazygames-sdk-v3\.js/);
assert.match(index, /css\/crazygames\.css/);
assert.match(main, /initCrazyGamesIntegration/);
assert.match(main, /crazyGamesGameplayStart/);
assert.match(main, /crazyGamesGameplayStop/);
assert.match(main, /requestCrazyGamesMidgameAd/);
assert.match(audio, /setPlatformAudioMuted/);
assert.match(chat, /cgDisableChat/);
assert.match(runtime, /addJoinRoomListener/);
assert.match(runtime, /updateRoom/);
assert.match(runtime, /isInstantMultiplayer/);
assert.equal(release.releaseId, 'cg1-r1-crazygames-basic-launch-readiness');
assert.equal(release.productVersion, '1.3.0-cg1-r1');
assert.equal(release.workerChangeRequired, false);
assert.equal(manifest.cg1.sdkV3, true);
assert.equal(manifest.cg1.webRtcAndCloudRelayPreserved, true);
console.log('CG.1 CrazyGames Basic Launch integration contract: PASS');
