import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8');
const release = JSON.parse(read('../release-version.json'));
const multiplayerRelease = JSON.parse(read('../multiplayer-release.json'));
const progressionCore = read('./progression_core.js');
const progression = read('./progression.js');
const loadoutCore = read('./loadout_core.js');
const loadout = read('./loadout.js');
const runtime = read('./loadout2_runtime.js');
const core = read('./loadout2_mastery_core.js');
const cloud = read('./cloud_profile.js');
const summary = read('./run_summary.js');
const updateDelivery = read('./update_delivery_core.js');
const build = read('../scripts/build_production.py');
const verifier = read('../scripts/verify_launch2_build.py');

assert.equal(release.releaseId, 'endgame1-r1-high-difficulty-operations');
assert.equal(release.productVersion, '1.11.0-endgame1-r1');
assert.equal(release.releaseSequence, 2026072301);
assert.equal(release.sourceBaselineSha, 'b99543d4f233d8d5284f48ae0c6df0d4a528a362');
assert.equal(release.workerChangeRequired, true);
assert.equal(multiplayerRelease.releaseLabel, 'ENDGAME.1 R1 - High-Difficulty Operations');
assert.equal(multiplayerRelease.loadout2.functionalFieldKnife, true);
assert.equal(multiplayerRelease.loadout2.pvpMeleeDisabled, true);
assert.equal(multiplayerRelease.loadout2.protocolUnchanged, true);
assert.match(progressionCore, /PROGRESSION_VERSION = 7/);
assert.match(progressionCore, /loadout2:/);
assert.match(progression, /recordProgressionLoadout2MasteryReceipt/);
assert.match(loadoutCore, /LOADOUT_PROFILE_VERSION = 2/);
assert.match(loadoutCore, /specializationId/);
assert.match(loadout, /LOADOUT2_SPECIALIZATIONS/);
assert.match(runtime, /beginLoadout2Run/);
assert.match(runtime, /finalizeLoadout2Run/);
assert.match(core, /idempotent/);
assert.match(cloud, /mergedLoadout2/);
assert.match(summary, /recordRunLoadout2Mastery/);
assert.match(updateDelivery, /endgame1-r1-high-difficulty-operations/);
assert.match(build, /LOADOUT2_PATCH/);
assert.match(verifier, /LOADOUT\.2 production manifest patch mismatch/);

console.log('LOADOUT.2 source integration contract passed');
