import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8');
const weapons = read('./weapons.js');
const controls = read('./controls.js');
const main = read('./main.js');
const cameraPresentation = read('./camera_presentation.js');
const command = read('./multiplayer/command_stream.js');
const remote = read('./multiplayer/remote_players.js');
const shared = read('./multiplayer/shared_world.js');
const html = read('../index.html');
const css = read('../css/hud.css');

assert.match(weapons, /export function meleeAttack\(\)/);
assert.match(weapons, /createFieldKnifeViewmodel/);
assert.match(weapons, /FIELD_KNIFE_FORWARD_POSE/);
assert.match(weapons, /forwardBladeAxis = '-Z'/);
assert.match(weapons, /setMeleeFirearmSuppressed\(true\)/);
assert.match(weapons, /group\.userData\.loadout2MeleeSuppressed/);
assert.match(weapons, /Readable center-line stab/);
assert.match(weapons, /FIELD_KNIFE_IMPACT_POSE/);
assert.match(weapons, /meleeSwingDuration = Math\.min\(0\.88, Math\.max\(0\.68/);

assert.match(weapons, /const FIELD_KNIFE_IMPACT_PROGRESS = 0\.66/);
assert.match(weapons, /const FIELD_KNIFE_BASE_DAMAGE = 36/);
assert.match(weapons, /const FIELD_KNIFE_BASE_RANGE = 1\.65/);
assert.match(weapons, /function resolveFieldKnifeImpact\(\)/);
assert.match(weapons, /if \(!meleeImpactResolved && progress >= FIELD_KNIFE_IMPACT_PROGRESS\)/);
const meleeAttackStart = weapons.indexOf('export function meleeAttack()');
const meleeUpdateStart = weapons.indexOf('function updateFieldKnifeViewmodel', meleeAttackStart);
assert.ok(meleeAttackStart >= 0 && meleeUpdateStart > meleeAttackStart);
const meleeAttackBlock = weapons.slice(meleeAttackStart, meleeUpdateStart);
assert.doesNotMatch(meleeAttackBlock, /findMeleeHit\(/);
assert.doesNotMatch(meleeAttackBlock, /processHit\(/);
const impactResolverStart = weapons.indexOf('function resolveFieldKnifeImpact()');
const impactResolverBlock = weapons.slice(impactResolverStart, meleeAttackStart);
assert.match(impactResolverBlock, /findMeleeHit\(/);
assert.match(impactResolverBlock, /processHit\(/);
assert.doesNotMatch(weapons, /Math\.round\(72 \*/);
assert.match(weapons, /enforceMeleeViewmodelExclusivity/);
assert.match(weapons, /if \(group\.parent\) group\.parent\.remove\(group\)/);
assert.match(weapons, /position: Object\.freeze\(\[0\.36, -0\.18, -0\.72\]\)/);
assert.doesNotMatch(weapons, /group\.rotation\.set\(-0\.44, -0\.48, 0\.34\)/);
assert.match(weapons, /weaponFamily: 'MELEE'/);
assert.match(weapons, /FIELD KNIFE DISABLED IN COMPETITIVE PVP/);
assert.match(controls, /MELEE: 'melee'/);
assert.match(controls, /defaultCode: 'KeyV'/);
assert.match(controls, /meleePressed = buttonPressed\(gamepad, 11\)/);
assert.match(main, /CONTROL_ACTIONS\.MELEE/);
assert.match(main, /bindTouchBtn\('btn-melee'/);
assert.match(cameraPresentation, /event\.code === 'KeyX'/);
assert.doesNotMatch(cameraPresentation, /event\.code === 'KeyV'/);
assert.match(command, /\['melee', 'KeyV', 'MELEE'\]/);
assert.match(remote, /action === 'MELEE'/);
assert.match(remote, /createMeleeModel/);
assert.match(shared, /weaponFamily === 'MELEE'/);
assert.match(shared, /reportedDistance > 3\.25/);
assert.match(html, /id="btn-melee"/);
assert.match(css, /#btn-melee/);

console.log('LOADOUT.2 functional Field Knife contract passed');
