// js/multiplayer/live_voice_turn_contract.test.js
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const source = await readFile(new URL('./live_voice_turn.js', import.meta.url), 'utf8');
const core = await readFile(new URL('./live_voice_turn_core.js', import.meta.url), 'utf8');
const main = await readFile(new URL('../main.js', import.meta.url), 'utf8');
const worker = await readFile(new URL('../../multiplayer-server/src/index.js', import.meta.url), 'utf8');
const workerCore = await readFile(new URL('../../multiplayer-server/src/voice_turn_core.js', import.meta.url), 'utf8');
const joined = `${source}\n${core}\n${main}\n${worker}\n${workerCore}`;
assert.doesNotMatch(main, /import ['"]\.\/multiplayer\/live_voice_turn\.js['"]/);
assert.match(source, /VOICE_ICE_CONFIG_REQUEST_ACTION/);
assert.match(source, /setConfiguration/);
assert.match(source, /TURN FALLBACK AVAILABLE/);
assert.match(source, /retryAll\?\./);
assert.match(worker, /VOICE_ICE_CONFIG_REQUEST_ACTION/);
assert.match(workerCore, /generate-ice-servers/);
assert.match(workerCore, /stun-only/);
assert.doesNotMatch(source, /TURN_KEY_ID|TURN_KEY_API_TOKEN/);
assert.doesNotMatch(joined, /MediaRecorder|audioChunk|audioData/);
console.log('live_voice_turn contract tests passed');
