import {canonicalM3ProgramCompletionJson,withoutDocumentSeal,createExpectedM3ProgramCompletionManifest,evaluateM3ProgramCompletionEvidence,createM3ProgramCompletionCertificate,createM3ProductionHandoff} from './m3_program_completion_core.js';
const byId=id=>document.getElementById(id);
const el={commit:byId('ka-m3-commit'),push:byId('ka-m3-push'),deployed:byId('ka-m3-deployed'),receiptFile:byId('ka-m3-receipt-file'),activationFile:byId('ka-m3-activation-file'),validate:byId('ka-m3-validate'),status:byId('ka-m3-status'),summary:byId('ka-m3-summary'),artifacts:byId('ka-m3-artifacts'),findings:byId('ka-m3-findings'),approver:byId('ka-m3-approver'),notes:byId('ka-m3-notes'),completeConfirm:byId('ka-m3-complete-confirm'),certificate:byId('ka-m3-certificate'),owner:byId('ka-m3-owner'),handoffConfirm:byId('ka-m3-handoff-confirm'),handoff:byId('ka-m3-handoff'),digest:byId('ka-m3-digest'),output:byId('ka-m3-output')};
let manifest=null,evaluation=null,receipt=null,activation=null,sealedCertificate=null;
async function sha256(text){const bytes=new TextEncoder().encode(text);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('');}
async function seal(value){const clone={...value};delete clone.documentSha256;return Object.freeze({...clone,documentSha256:await sha256(canonicalM3ProgramCompletionJson(clone))});}
async function verifySeal(value){if(!value || typeof value!=='object' || !/^[a-f0-9]{64}$/i.test(String(value.documentSha256||''))) return false;return (await sha256(canonicalM3ProgramCompletionJson(withoutDocumentSeal(value))))===String(value.documentSha256).toLowerCase();}
async function fetchText(url){const response=await fetch(url,{cache:'no-store'});const text=await response.text();if(!response.ok)throw new Error(`${url} returned HTTP ${response.status}`);return {text,status:response.status};}
async function fetchJson(url){const {text,status}=await fetchText(url);return {value:JSON.parse(text),text,status};}
async function readJsonFile(input,label){const file=input.files?.[0];if(!file)throw new Error(`${label} JSON file is required.`);return JSON.parse(await file.text());}
function download(name,value){const blob=new Blob([JSON.stringify(value,null,2)+'\n'],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function show(value){el.output.textContent=JSON.stringify(value,null,2);el.digest.textContent=value?.documentSha256||'—';}
function render(){const ready=evaluation?.ready===true;el.status.textContent=ready?'PASS':'BLOCKED';el.status.dataset.tone=ready?'success':'danger';el.summary.textContent=ready?'All final M3 evidence is valid. M3.100 completion may now be sealed.':'Final M3 evidence is incomplete or mismatched.';el.findings.replaceChildren();for(const item of [...(evaluation?.errors||[]),...(evaluation?.warnings||[])]){const li=document.createElement('li');li.textContent=`${item.code}: ${item.message}`;el.findings.append(li);}el.certificate.disabled=!ready;el.handoff.disabled=!sealedCertificate;}
async function validate(){el.validate.disabled=true;el.status.textContent='CHECKING';el.summary.textContent='Verifying public M3.97 artifacts, release identity, and sealed evidence…';try{manifest=(await fetchJson('./m3-program-completion.json')).value;const expected=createExpectedM3ProgramCompletionManifest();const artifactChecks=[];el.artifacts.replaceChildren();for(const [path,expectedSha256] of Object.entries(expected.expectedAutomaticPagesArtifactSha256)){let actualSha256='',httpStatus=0,ok=false;try{const result=await fetchText(new URL('/'+path.replace(/^\/+/,''),expected.frontendUrl));httpStatus=result.status;actualSha256=await sha256(result.text);ok=actualSha256===expectedSha256;}catch{}artifactChecks.push({path,expectedSha256,actualSha256,httpStatus,ok});const li=document.createElement('li');li.textContent=`${ok?'PASS':'FAIL'} ${path}`;el.artifacts.append(li);}const frontendRelease=(await fetchJson(new URL(expected.frontendReleaseManifestPath,expected.frontendUrl))).value;const workerRelease=(await fetchJson(new URL('/release',expected.workerUrl))).value;receipt=await readJsonFile(el.receiptFile,'Pages deployment receipt');activation=await readJsonFile(el.activationFile,'Maintenance activation');const receiptSealValid=await verifySeal(receipt);const activationSealValid=await verifySeal(activation);evaluation=evaluateM3ProgramCompletionEvidence({manifest,productionOrigin:location.origin,submittedCommitSha:el.commit.value,githubPushConfirmed:el.push.checked,automaticDeploymentConfirmed:el.deployed.checked,artifactChecks,frontendRelease,workerRelease,deploymentReceipt:receipt,deploymentReceiptSealValid:receiptSealValid,maintenanceActivation:activation,maintenanceActivationSealValid:activationSealValid});sealedCertificate=null;render();show({evaluation,receiptSealValid,activationSealValid,artifactChecks});}catch(error){evaluation=null;sealedCertificate=null;el.status.textContent='ERROR';el.status.dataset.tone='danger';el.summary.textContent=error.message;el.certificate.disabled=true;el.handoff.disabled=true;show({error:error.message});}finally{el.validate.disabled=false;}}
el.validate.addEventListener('click',validate);
el.certificate.addEventListener('click',async()=>{try{const value=createM3ProgramCompletionCertificate({evaluation,deploymentReceipt:receipt,maintenanceActivation:activation,approver:el.approver.value,notes:el.notes.value,completionConfirmed:el.completeConfirm.checked});sealedCertificate=await seal(value);show(sealedCertificate);el.handoff.disabled=false;download('khadijas-arena-m3-100-program-completion-certificate.json',sealedCertificate);}catch(error){alert(error.message);}});
el.handoff.addEventListener('click',async()=>{try{const value=createM3ProductionHandoff({completionCertificate:sealedCertificate,completionCertificateSha256:sealedCertificate?.documentSha256,productionOwner:el.owner.value,handoffConfirmed:el.handoffConfirm.checked});const sealed=await seal(value);show(sealed);download('khadijas-arena-m3-100-production-handoff.json',sealed);}catch(error){alert(error.message);}});
