import assert from 'node:assert/strict';
import {deriveMultiplayerProductionReleaseUiState,MULTIPLAYER_PRODUCTION_RELEASE_UI_PATCH} from './production_release_ui_core.js';
assert.equal(MULTIPLAYER_PRODUCTION_RELEASE_UI_PATCH,'m3-production-release-ui-r2-launch');
const idle = deriveMultiplayerProductionReleaseUiState();
assert.equal(idle.blockActions,false);
assert.equal(idle.statusText,'ONLINE SERVICES STANDBY');
assert.equal(idle.retryVisible,false);
const checking = deriveMultiplayerProductionReleaseUiState({productionRelease:{status:'CHECKING',blocking:true}});
assert.equal(checking.retryDisabled,true);
assert.equal(checking.statusText,'CONNECTING TO ONLINE SERVICES…');
const ready = deriveMultiplayerProductionReleaseUiState({productionRelease:{status:'PASS',ready:true}});
assert.equal(ready.status,'PASS');
assert.equal(ready.statusText,'ONLINE SERVICES READY');
const failed = deriveMultiplayerProductionReleaseUiState({productionRelease:{status:'FAIL',blocking:true,errors:[{message:'internal mismatch detail'}]}});
assert.equal(failed.blockActions,true);
assert.equal(failed.statusText,'ONLINE SERVICES TEMPORARILY UNAVAILABLE');
assert.equal(failed.statusText.includes('mismatch'),false);
console.log('production_release_ui_core launch-safe tests passed');
