import {
  canonicalProductionMaintenanceJson,evaluateProductionMaintenanceEvidence,createCertifiedMaintenanceBaseline,
  classifyProductionMaintenanceChange,createMaintenanceChangeAuthorization
} from './production_maintenance_control_core.js';

const byId=id=>document.getElementById(id);
const elements={
  archiveFile:byId('ka-maintenance-archive-file'),archive:byId('ka-maintenance-archive'),runbookFile:byId('ka-maintenance-runbook-file'),runbook:byId('ka-maintenance-runbook'),
  validate:byId('ka-maintenance-validate'),status:byId('ka-maintenance-status'),summary:byId('ka-maintenance-summary'),findings:byId('ka-maintenance-findings'),
  owner:byId('ka-maintenance-owner'),notes:byId('ka-maintenance-notes'),baselineConfirm:byId('ka-maintenance-baseline-confirm'),baselineExport:byId('ka-maintenance-baseline-export'),
  ticket:byId('ka-maintenance-ticket'),approver:byId('ka-maintenance-approver'),changeSummary:byId('ka-maintenance-change-summary'),paths:byId('ka-maintenance-paths'),workerCode:byId('ka-maintenance-worker-code'),
  protocol:byId('ka-maintenance-protocol'),build:byId('ka-maintenance-build'),releasePatch:byId('ka-maintenance-release-patch'),changeConfirm:byId('ka-maintenance-change-confirm'),
  classify:byId('ka-maintenance-classify'),authorizationExport:byId('ka-maintenance-authorization-export'),classification:byId('ka-maintenance-classification'),digest:byId('ka-maintenance-digest'),output:byId('ka-maintenance-output')
};
let manifest=null,archive=null,runbook=null,evaluation=null,sealedBaseline=null,classification=classifyProductionMaintenanceChange();
function parseJson(text,label){ try{return JSON.parse(text);}catch(error){throw new Error(`${label} is not valid JSON: ${error.message}`);} }
async function sha256(text){ const bytes=new TextEncoder().encode(text); const digest=await crypto.subtle.digest('SHA-256',bytes); return [...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join(''); }
async function verifySealedDocument(value){ if(!value||typeof value!=='object'||Array.isArray(value)) return false; const expected=String(value.documentSha256||'').toLowerCase(); if(!/^[a-f0-9]{64}$/.test(expected)) return false; const clone={...value}; delete clone.documentSha256; return await sha256(canonicalProductionMaintenanceJson(clone))===expected; }
async function seal(value){ const clone={...value}; delete clone.documentSha256; return Object.freeze({...clone,documentSha256:await sha256(canonicalProductionMaintenanceJson(clone))}); }
function downloadJson(name,value){ const blob=new Blob([JSON.stringify(value,null,2)+'\n'],{type:'application/json'}); const url=URL.createObjectURL(blob); const anchor=document.createElement('a'); anchor.href=url; anchor.download=name; anchor.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
function bindFile(input,textarea){ input.addEventListener('change',async()=>{const file=input.files?.[0]; if(file) textarea.value=await file.text();}); }
function showOutput(value){ elements.output.textContent=JSON.stringify(value,null,2); elements.digest.textContent=value?.documentSha256||'—'; }
function renderEvidence(){ const ready=evaluation?.ready===true; elements.status.textContent=ready?'PASS':'BLOCKED'; elements.status.dataset.tone=ready?'success':'danger'; elements.summary.textContent=ready?'Archive and recovery chain are valid. The permanent archive does not expire.':'Maintenance evidence is incomplete or invalid.'; elements.findings.replaceChildren(); for(const item of [...(evaluation?.errors||[]),...(evaluation?.warnings||[])]){const li=document.createElement('li'); const strong=document.createElement('strong'); strong.textContent=item.code; li.append(strong,document.createTextNode(item.message)); elements.findings.append(li);} elements.baselineExport.disabled=!ready||!elements.baselineConfirm.checked||!elements.owner.value.trim(); renderChange(); }
function renderChange(){ elements.classification.textContent=classification.scope; elements.authorizationExport.disabled=!(sealedBaseline?.documentSha256&&classification.ready===true&&elements.changeConfirm.checked&&elements.ticket.value.trim()&&elements.approver.value.trim()&&elements.changeSummary.value.trim()); }
async function validateEvidence(){ if(!manifest){const response=await fetch('./production-maintenance-control.json',{cache:'no-store'}); if(!response.ok) throw new Error(`Maintenance manifest request failed: ${response.status}`); manifest=await response.json();} archive=parseJson(elements.archive.value,'Certified archive'); runbook=parseJson(elements.runbook.value,'Recovery runbook'); const [archiveDigestValid,runbookDigestValid]=await Promise.all([verifySealedDocument(archive),verifySealedDocument(runbook)]); evaluation=evaluateProductionMaintenanceEvidence({manifest,certifiedArchive:archive,archiveDigestValid,recoveryRunbook:runbook,runbookDigestValid}); sealedBaseline=null; renderEvidence(); return evaluation; }
function classifyChange(){ classification=classifyProductionMaintenanceChange({affectedPaths:elements.paths.value,workerCodeChanged:elements.workerCode.checked,proposedProtocol:elements.protocol.value,proposedBuild:elements.build.value,proposedReleasePatch:elements.releasePatch.value}); renderChange(); showOutput(classification); return classification; }
bindFile(elements.archiveFile,elements.archive); bindFile(elements.runbookFile,elements.runbook);
elements.validate.addEventListener('click',()=>validateEvidence().catch(error=>alert(error.message)));
for(const element of [elements.owner,elements.baselineConfirm,elements.ticket,elements.approver,elements.changeSummary,elements.changeConfirm]) element.addEventListener('input',()=>{if(evaluation)renderEvidence();else renderChange();});
elements.classify.addEventListener('click',()=>{try{classifyChange();}catch(error){alert(error.message);}});
elements.baselineExport.addEventListener('click',async()=>{try{const payload=createCertifiedMaintenanceBaseline(evaluation,archive,runbook,{owner:elements.owner.value,confirmation:elements.baselineConfirm.checked,notes:elements.notes.value}); sealedBaseline=await seal(payload); showOutput(sealedBaseline); downloadJson('khadijas-arena-certified-maintenance-baseline.json',sealedBaseline); renderChange();}catch(error){alert(error.message);}});
elements.authorizationExport.addEventListener('click',async()=>{try{classification=classifyChange(); const payload=createMaintenanceChangeAuthorization(sealedBaseline,classification,{ticket:elements.ticket.value,approver:elements.approver.value,summary:elements.changeSummary.value,confirmation:elements.changeConfirm.checked}); const sealed=await seal(payload); showOutput(sealed); downloadJson('khadijas-arena-maintenance-change-authorization.json',sealed);}catch(error){alert(error.message);}});
renderEvidence();
